### ISSUE TITLE
Issues running cbench

### ISSUE THREAD

**Issue by hugozidos** [mininet/oflops#7]
I am having issues running cbench on ubuntu 20.04. I am running it from within the oflops directory but I keep getting this error saying the ./cbench: command not found.

And when I try to run as "bench", it throws up this error:
Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py", line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

I am not sure how to go about resolving this..i have been stuck on this for a while now.

**Comment by hugozidos** [comment]
I used option 2 in the mininet walkthrough site: http://mininet.org/download/

this helped
